### ISSUE TITLE
How is the compatibility with intel-nvidia models?

### ISSUE THREAD

**Issue by AgustinCeballos37** [ExtremeXT/Lenovo_Legion_5_Hackintosh#16]
sorry if not a issue im learning how to use the whole version control.
https://www.youtube.com/watch?v=UFW18Cppswc

**Comment by ExtremeXT** [comment]
> sorry if not a issue im learning how to use the whole version control.

@AgustinCeballos37 This repository only works with AMD dGPU laptops. You can join a forum such [Noot](https://t.me/NootInc) for help on making your own EFI for your laptop.
