### ISSUE TITLE
The screen brightness cannot be adjusted and cannot sleep

### ISSUE THREAD

**Issue by jk110** [ExtremeXT/Lenovo_Legion_5_Hackintosh#3]
The screen brightness cannot be adjusted and cannot sleep
屏幕亮度没法调节和不能休眠

**Comment by zty199** [comment]
Use Monitor Control Lite in App Store.

---
已知问题，可以暂时从商店下载 Monitor Control Lite 调节亮度。原生亮度可能需要自定义 ACPI 亮度，可以参考 OC-little 项目试试。

**Comment by juenuo** [comment]
quickshade 可以调节亮度

**Comment by ExtremeXT** [comment]
English only! Non-English issues are not accepted.
