### ISSUE TITLE
The system crashes once an hour

### ISSUE THREAD

**Issue by jk110** [ExtremeXT/Lenovo_Legion_5_Hackintosh#4]
![image](https://user-images.githubusercontent.com/56330712/195266876-dd74d2b1-e360-477d-9be7-fee6527a5148.png)

The system crashes once an hour
系统太概一小时会崩溃一次

log：[log.zip](https://github.com/extremegrief1/Lenovo_Legion_5_Hackintosh/files/9762154/log.zip)

**Comment by extremegrief1** [comment]
> ![image](https://user-images.githubusercontent.com/56330712/195266876-dd74d2b1-e360-477d-9be7-fee6527a5148.png)
> 
> The system crashes once an hour 系统太概一小时会崩溃一次
> 
> log：[log.zip](https://github.com/extremegrief1/Lenovo_Legion_5_Hackintosh/files/9762154/log.zip)

Are you using the dGPU exclusively?

**Comment by ExtremeXT** [comment]
Should be fixed in some earlier commit.
