### ISSUE TITLE
联想R7000P不能用此EFI直接安装系统，必须借助别的机器安装好12.6版本系统进固态，用此EFI才能启动。必须是12.6系统

### ISSUE THREAD

**Issue by juenuo** [ExtremeXT/Lenovo_Legion_5_Hackintosh#6]
系统BIOS设置默认，不需任何改动，默认就是关闭安全启动。
能用usb鼠标。不能用usb存储U盘啥的，能adb连接手机。
触摸板不能用，亮度只能软件调节

**Comment by yshen22** [comment]
> 系统BIOS设置默认，不需任何改动，默认就是关闭安全启动。
> 能用usb鼠标。不能用usb存储U盘啥的，能adb连接手机。
> 触摸板不能用，亮度只能软件调节

12.6.2系统可以启动吗？

**Comment by saiGou-14H** [comment]
不用其他固态还有办法安装吗

**Comment by xialer** [comment]
求助,我使用vmware workstation直接在另一块硬盘上安装了12.6,然后使用deskgen将efi里面的内容拷贝到引导分区.
但是,重启之后,应该是过了opencore初始化部分,快到进度条出现的时候然后黑屏,没有任何文字的黑屏,没有响应,循环重启....
周而复始

**Comment by ExtremeXT** [comment]
English only. If you provide proper information in English, issue will be reopened.
