### ISSUE TITLE
Legion 5 6th Gen 6600m, there is no sound after booting with this EFI, how to solve it?

### ISSUE THREAD

**Issue by alpahremo1** [ExtremeXT/Lenovo_Legion_5_Hackintosh#7]
Hello, my laptop is also Legion 5 6th Gen. The configuration is exactly the same as yours. Audio is Realtek ALC287. After booting Monterey 12.6 with this EFI, there is no sound. How to solve it?Thank you so much!

**Comment by alpahremo1** [comment]
i taied to modifited alcid from 11 to 21,then it works!

**Comment by yshen22** [comment]
> Hello, my laptop is also Legion 5 6th Gen. The configuration is exactly the same as yours. Audio is Realtek ALC287. After booting Monterey 12.6 with this EFI, there is no sound. How to solve it?Thank you so much!

Did you install from USB flash without error using this EFI?

**Comment by kalkmann** [comment]
Follow https://forum.amd-osx.com/threads/amd-rayon-r7-5800h-install-monterey-kernel-panic.2725/

**Comment by kalkmann** [comment]
> > Hello, my laptop is also Legion 5 6th Gen. The configuration is exactly the same as yours. Audio is Realtek ALC287. After booting Monterey 12.6 with this EFI, there is no sound. How to solve it?Thank you so much!
> 
> Did you install from USB flash without error using this EFI?

Follow https://forum.amd-osx.com/threads/amd-rayon-r7-5800h-install-monterey-kernel-panic.2725/

**Comment by ExtremeXT** [comment]
Fixed in some older commit.
