### ISSUE TITLE
Use your efi to start, but the computer keeps rebooting

### ISSUE THREAD

**Issue by SunSgr** [ExtremeXT/Lenovo_Legion_5_Hackintosh#8]
Hello, my current system is the latest, the same as yours, but I tried to close xhci1 and use your efi to start, but the computer kept restarting, using -v instruction, but the restart speed is too fast, can't see the specific reason

**Comment by ExtremeXT** [comment]
> Hello, my current system is the latest, the same as yours, but I tried to close xhci1 and use your efi to start, but the computer kept restarting, using -v instruction, but the restart speed is too fast, can't see the specific reason

Do you have Discord or Telegram?

**Comment by Gradi0us** [comment]
> Hello, my current system is the latest, the same as yours, but I tried to close xhci1 and use your efi to start, but the computer kept restarting, using -v instruction, but the restart speed is too fast, can't see the specific reason

Have you ever tried using UMAF before? Could you list all the disks you have, such as NVME or SATA SSD, and check if they are on the whitelist? I had a similar problem before, where one of my NVME disks was not compatible with Hackintosh. When I unplugged it from the machine, the Hackintosh ran perfectly.

**Comment by SunSgr** [comment]
> > Hello, my current system is the latest, the same as yours, but I tried to close xhci1 and use your efi to start, but the computer kept restarting, using -v instruction, but the restart speed is too fast, can't see the specific reason
> 
> Do you have Discord or Telegram?

https://t.me/+jAcNaFw3Kww2YmY9

**Comment by ExtremeXT** [comment]
> > > Hello, my current system is the latest, the same as yours, but I tried to close xhci1 and use your efi to start, but the computer kept restarting, using -v instruction, but the restart speed is too fast, can't see the specific reason
> > 
> > 
> > Do you have Discord or Telegram?
> 
> https://t.me/+jAcNaFw3Kww2YmY9

I cannot talk there, give me your user.

**Comment by SunSgr** [comment]
> 

I have sent you a message, by telegram

**Comment by SunSgr** [comment]
> > Hello, my current system is the latest, the same as yours, but I tried to close xhci1 and use your efi to start, but the computer kept restarting, using -v instruction, but the restart speed is too fast, can't see the specific reason
> 
> Have you ever tried using UMAF before? Could you list all the disks you have, such as NVME or SATA SSD, and check if they are on the whitelist? I had a similar problem before, where one of my NVME disks was not compatible with Hackintosh. When I unplugged it from the machine, the Hackintosh ran perfectly.
I turned off xhci1, my nvme can be used, currently using another efi can boot normally, but not usb

**Comment by ExtremeXT** [comment]
Should be fixed. Let me know.
